@startuml
title Процесс оформления заказа

|Покупатель|
start
repeat
:Выбрать товар и поместить его в корзину;
|API Gateway Service|
if(Пользователь аутентифицирован?) then (да)
    :Получить из JWT UserID;
    :Добавить в header X-UserID
    (или упаковать в JWT);
endif
|Order Service|
if(В запросе есть CartId?) then(нет)
    :Создать новую корзину;
    if(Пользователь аутентифицирован?) then (да)
        :Получить данные о способе доставки и оплаты
        из предедущего заказа пользователя;
        |Discount Service|
        :Получить сумму/процент скидки;
    endif
else(да)
endif
|Product Service|
:Получить цену добавленного продукта;
|Order Service|
:Добавить в корзину продукт;
:Пересчитать сумму заказа;
|Покупатель|
repeat while (Добавить еще товар в корзину?)

:Заполнить информацию о заказе в корзине
(способ оплаты и доставки);
:Нажать кнопку "Подтверждаю заказ";

|API Gateway Service|
if(Пользователь аутентифицирован?) then(да)
    :Получить из JWT UserID
    (или упаковать в JWT);
else (нет)
    if(номер телефона указан
    в правильном формате) then(нет)
        |Покупатель|
        :Ответ 400;
        end
    else (да)
        |User Service|
        :Получить по номеру телефона UserID;
    endif
    if(UserID найден по номеру телефона) then(нет)
        |User Service|
        :Зарегистрировать нового покупателя
        и вернуть UserID;
        |Message broker|
        :Сообщить об автоматическом
        создании нового пользователя
        Читатели:
        - Notification service (отправка приветствия)
        - Notification service (запрос на смену пароля);
    else(да)
    endif
|API Gateway Service|
endif
:Добавить в header X-UserID;
|Order Service|
if(в заказе нет ошибок?
    - правильный номер телефона
    - есть X-UserID
    - есть имя
    - заказ не пустой
    - заказ не продублирован) then (есть)
        |Покупатель|
        :Ответ 400;
        end
else(нет ошибок)
|Order Service|
:Транзакционно:
- создать заказ со
  статусом "Ожидается подтверждение"
- удалить корзину
Ретраем:
- списать балы со скидочной карты (асинхронно);
|Message broker|
        :Сообщить об создании нового заказа
        Читатели:
        - Notification service (Сообщить менеджеру о
          создании нового заказа)
        - Notification service (Отправить сообщение покупателю)
        - Discount Service (списать балы);
|Order Service|
if(Оплата кредитной картой Visa/Mastercard?)then(нет)
    |Покупатель|
    :Показать пользователю номер заказа
    и сообщение, что с ним свяжутся;
    end;
else(да)
    |Order Service|
    if(в заказе есть ошибки:
        - указаны размеры) then(да)
      |Покупатель|
          :Показать пользователю номер заказа
          и сообщение, что с ним свяжутся;
          end;
    |Order Service|
    else(нет)
        :Транзакционно:
        - списываем со склада пары в заказе
        - меняем статус заказа на "Ожидается оплата";
        |Message broker|
        :Сообщить об изменении статуса заказа
         Читатели:
         - Notification service (сообщение покупателю);
        |Order Service|
        :;
        |Payment Service|
        :Запрос ссылки для оплаты заказа
        от провайдера услуг;
        fork
            |Провайдерами приема оплат|
            :Получить ссылку для оплаты;
            |Payment Service|
            :Сохранить токен для авторизации
            подтверждения заказа;
            |Message broker|
                    :Сообщить об получении ссылки для оплаты
                     Читатели:
                     - Order Service (Привязать ссылку к заказу)
                     - Notification Service (Отправить сообщение покупателю);
            detach
            fork again
            |Order Service|
            :;
            |Покупатель|
            :Показать покупателю номер заказа
            Сообщит от тома, что заказ забронирован
            Сообщить, что бы ожидал ссылку на оплату;
            endfork
            while(получить ссылку на оплату) is(нет ссылки)
                |Order Service|
                :Получить ссылку;
            endwhile (есть ссылка)
            |Покупатель|
            :Показать ссылку на оплату;
            end
@enduml