@startuml
title Оформление заказа (оплата при получении)
skinparam maxmessagesize 150

actor Покупатель as User
participant "FrontEnd" as FrontEnd
participant "Backend" as Backend
actor Менеджер as Manager
actor Кладовщик as StockMan

User -> FrontEnd: Выбор товара
User -> FrontEnd: Помещение товара в корзину
FrontEnd -> Backend: Создание заказа
Backend --> FrontEnd: Информация о заказе (номер заказа)
FrontEnd --> User: Спасибо за заказ, Ваш номер заказа ..., с Вами свяжутся для уточнения деталей

==  ==
Backend -> Manager: Информировании о новом заказе
Manager -> User: Уточнение деталей заказа.
User --> Manager:
Manager -> Backend: Изменить статус на "Ожидается отправка (Оплата при получении)"
Backend -> User: Информировании об изменении статуса заказа.
==  ==
Backend -> Backend: Создание декларации службы доставки
Backend -> StockMan: Информировании о новом заказе для отправки
StockMan -> Backend: Создание чека.
Backend --> StockMan:
StockMan -> StockMan: Подготовка и отправка заказа
StockMan -> Backend: Изменить статус заказа на "Заказ отправлен"
Backend -> User: Информировании об изменении статуса заказа.


@enduml