@startuml
title Процесс подтверждения заказа при оплате кредитной картой Visa/Mastercard
|Покупатель|
start
:Переход по ссылке
для совершения оплаты и совершение оплаты;
|Провайдер приема оплат|
if(Оплата произведена успешно?) then(нет)
    |Покупатель|
    :Ошибка совершения оплаты;
    end
else(да)
|Провайдер приема оплат|
:Сообщить ИМ об успешной оплате;
endif
|Payment Service|
repeat
:Зафиксировать оплату;
|Message broker|
:Сообщить об оплате заказа
Читатели:
- Order Service (изменить статус заказа на "Ожидается оплата"),
- Notification Service (Отправить сообщение покупателю),
- Bills Service(формирование чека);
|Покупатель|
:Сообщить об успешной оплате;
end
|Payment Service|
start
:Переодически проверять неоплаченные заказа
На тот случай, если покупатель оплатил заказ,
но до сервиса эта информация не дошла;
|Провайдер приема оплат|
:Вернуть статус счета;
|Payment Service|
if(счет оплачен?) then (нет)
    end
else(да)
endif
    repeat while ()
@enduml