@startuml
title Процесс подтверждения заказа при оплате на карту или поплате при получении
|Менеджер|
start
:Есть информация о новом заказе
со статусом "Ожидается подтверждение";
:Уточнить у клиента детали заказа;
if(нужно менять заказ)then(да)
|Order service|
if(заказ находится в том статусе, когда можно изменять заказ?
    Ожидается подтверждение: можно менять всё
    Ожидается оплата: только информация о доставке) then (нет)
    |Менеджер|
    :Ответ 400;
    end
else(да)
    |Order service|
    :Внести изменение о заказе;
    |Message broker|
            :Сообщить об изменении заказа
            Читатели:
            - Notification service (отправка сообщение покупателю);
endif
else(нет)
endif
|Менеджер|
if(Заказ отменен?)then(да)
    |Order service|
    if(заказ можно отменять?)then(да)
        :Поменять статус заказа на "Заказ отмене";
        |Message broker|
                    :Сообщить об изменении заказа
                    Читатели:
                    - Notification service (отправка сообщение покупателю)
                    - Product service (добавить продукт в наличие)
                    - Discount Service (добавить списанные в заказ балы)
                    - Payment Service (отменить счет на оплату)
                    - Bills Service(отменить чек);
    else(нет)
        |Менеджер|
         :Ответ 400;
         end
    endif
else(нет)
endif
|Менеджер|
if(Покупатель хочет оплатить заказ при получении?)then(да)
    |Order service|
    :Транзакционно:
    Списать пары со склада (Product service)
    Поменять статус заказа на "Ожидается отправка";
    |Message broker|
    :Сообщить об изменении заказа
    Читатели:
    - Notification service (отправка сообщение покупателю)
    - Delivery Service (создание декларации);
else(нет)
endif
|Менеджер|
if(Покупатель хочет оплатить заказ карту)then(да)
    |Order service|
        :Транзакционно:
        Списать пары со склада (Product service)
        Поменять статус заказа на "Ожидается оплата";
        |Message broker|
        :Сообщить об изменении заказа
        Читатели:
        - Notification service (отправка сообщение покупателю)
        - Payment Service (Создать счет об оплате);
else(нет)
endif
|Менеджер|
end

@enduml